### PR TITLE
WIP: add types, BeeGFS 7 support, admon, RPM install

### PR DESCRIPTION
**Pull request by runejuhl**
Hi!

I've made a whole bunch of changes and additions and was wondering if it's something you'd like to merge into your repo. Currently it's these two large commits, but if you'd like I can squash them ( -- or split them into smaller chunks).

+ adds Puppet types almost everywhere
+ adds BeeGFS 7 support with templates copied from a clean install (to expose all options)
+ adds support for setting up admon
+ adds Yum repo and RPM install

So far it's untested on anything other than CentOS 7.

If you're interested in merging this please let me know what needs to be done to make it proper.

### CODE REVIEW

**Comment by deric** [comment]
That's quite a lot of changes! Thanks for the effort, so far it looks good to me. I haven't tested the code yet, but the changes should be reflected in the README (renaming `major_version` to `release`).

**Comment by runejuhl** [comment]
Great! I'll see if I can find some time this week for making sure tests pass and make the changes to README.

**Comment by lschweiss-wustl** [comment]
It would be great to get this PR merged.  I've been using the mods by runjuhl for several months without issue.

**Comment by runejuhl** [comment]
@lschweiss-wustl yes, I guess this was a bit overdue... :smile: 

I fixed the linter errors and tried running acceptance tests. I believe I did the same back in December, but I can't get it to work now:

~~~
$ bundle exec rake acceptance 
Warning: Puppet's internal vendored libraries are Private APIs and can change without warning. The 'semantic' library has been replaced with 'semantic_puppet'.
/usr/bin/ruby2.5 -I/home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.0/lib:/home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.0/lib /home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.0/exe/rspec spec/acceptance
/home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/beaker-rspec-6.2.4/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/specinfra-2.77.2/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Hypervisor for ubuntu-server-1204-x64 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create

An error occurred while loading ./spec/acceptance/class_spec.rb.
Failure/Error: require 'beaker-rspec/spec_helper'
LoadError:
  cannot load such file -- beaker/hypervisor/vagrant
  
# ./vendor/bundle/ruby/2.5.0/gems/beaker-4.7.0/lib/beaker/hypervisor.rb:31:in `require'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-4.7.0/lib/beaker/hypervisor.rb:31:in `create'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-4.7.0/lib/beaker/network_manager.rb:72:in `block in provision'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-4.7.0/lib/beaker/network_manager.rb:71:in `each_key'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-4.7.0/lib/beaker/network_manager.rb:71:in `provision'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-rspec-6.2.4/lib/beaker-rspec/beaker_shim.rb:35:in `provision'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-rspec-6.2.4/lib/beaker-rspec/spec_helper.rb:50:in `block in <top (required)>'
# ./vendor/bundle/ruby/2.5.0/gems/beaker-rspec-6.2.4/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
# ./spec/spec_helper_acceptance.rb:1:in `require'
# ./spec/spec_helper_acceptance.rb:1:in `<top (required)>'
# ./spec/acceptance/class_spec.rb:1:in `require'
# ./spec/acceptance/class_spec.rb:1:in `<top (required)>'
No examples found.

Finished in 0.00023 seconds (files took 1.04 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/usr/bin/ruby2.5 -I/home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.0/lib:/home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.0/lib /home/runejuhl/opt/puppet-beegfs/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.0/exe/rspec spec/acceptance failed
~~~

Any hints?

**Comment by deric** [comment]
Acceptance tests aren't properly configured in the master anyway. We can fix this in separate PRs, it will be much easier to review. Now it seems that tests are failing for `puppet < 4.9`. Do we want to cover older Puppet versions? It might not be so hard to fix..

**Pull request merged**
